"""Initial migration

Revision ID: 9188474c90c6
Revises: 
Create Date: 2025-06-27 09:34:54.968233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9188474c90c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_connections_email'), table_name='email_connections')
    op.drop_index(op.f('ix_email_connections_user_email'), table_name='email_connections')
    op.drop_table('email_connections')
    op.drop_table('grn')
    op.drop_table('email_records')
    op.drop_table('documents')
    op.drop_table('invoice_header_master')
    op.drop_table('three_way_match')
    op.drop_table('line_items_po_invoice_dc_format2')
    op.drop_table('dc_header_master')
    op.drop_table('emailrecord')
    op.drop_table('vendor_details')
    op.drop_table('po_header_master')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('line_items_po_invoice_dc_format_1')
    op.drop_table('item_master')
    op.drop_table('sub_description_line_items_format_2')
    op.drop_table('email_sync_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_sync_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('auto_sync', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_folders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('email_documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sync_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['email_connections.id'], name=op.f('email_sync_settings_connection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_sync_settings_pkey')),
    sa.UniqueConstraint('connection_id', name=op.f('email_sync_settings_connection_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sub_description_line_items_format_2',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('line_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sub_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sub_description_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items_po_invoice_dc_format2.line_item_id'], name=op.f('sub_description_line_items_format_2_line_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sub_description_line_items_format_2_pkey'))
    )
    op.create_table('item_master',
    sa.Column('item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('item_id', name='item_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('line_items_po_invoice_dc_format_1',
    sa.Column('line_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('doc_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hsn_sac', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('overall_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remaining_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grn_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gst_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.item_id'], name=op.f('line_items_po_invoice_dc_format_1_item_id_fkey')),
    sa.PrimaryKeyConstraint('line_item_id', name=op.f('line_items_po_invoice_dc_format_1_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('po_header_master',
    sa.Column('po_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('po_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('overall_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_gst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_amount_after_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='po_header_master_document_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_details.id'], name='po_header_master_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('po_id', name='po_header_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vendor_details',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gst_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vendor_details_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('emailrecord',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_uid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_attachment_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachment_file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_id_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('received_date_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachment_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachment_num_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doc_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('emailrecord_pkey'))
    )
    op.create_table('dc_header_master',
    sa.Column('dc_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dc_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('po_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('overall_tax_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='dc_header_master_document_id_fkey'),
    sa.ForeignKeyConstraint(['po_id'], ['po_header_master.po_id'], name='dc_header_master_po_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_details.id'], name='dc_header_master_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('dc_id', name='dc_header_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('line_items_po_invoice_dc_format2',
    sa.Column('line_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('doc_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hsn_sac', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('overall_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remaining_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grn_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gst_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.item_id'], name=op.f('line_items_po_invoice_dc_format2_item_id_fkey')),
    sa.PrimaryKeyConstraint('line_item_id', name=op.f('line_items_po_invoice_dc_format2_pkey'))
    )
    op.create_table('three_way_match',
    sa.Column('match_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('po_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dc_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('discrepancy_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['dc_header_master.dc_id'], name='three_way_match_dc_id_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice_header_master.invoice_id'], name='three_way_match_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['po_id'], ['po_header_master.po_id'], name='three_way_match_po_id_fkey'),
    sa.PrimaryKeyConstraint('match_id', name='three_way_match_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('invoice_header_master',
    sa.Column('invoice_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('po_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('overall_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_gst_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_amount_after_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='invoice_header_master_document_id_fkey'),
    sa.ForeignKeyConstraint(['po_id'], ['po_header_master.po_id'], name='invoice_header_master_po_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_details.id'], name='invoice_header_master_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('invoice_id', name='invoice_header_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('documents',
    sa.Column('document_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('email_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_id_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('received_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doc_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['email_connections.id'], name=op.f('email_records_connection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_records_pkey'))
    )
    op.create_table('grn',
    sa.Column('grn_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('erp_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['three_way_match.match_id'], name=op.f('grn_match_id_fkey')),
    sa.PrimaryKeyConstraint('grn_id', name=op.f('grn_pkey'))
    )
    op.create_table('email_connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('connection_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imap_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('smtp_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('CONNECTED', 'DISCONNECTED', 'SYNCING', 'FAILED', name='connectionstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('email_connections_user_email_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_connections_pkey')),
    sa.UniqueConstraint('email', 'user_email', name=op.f('uq_user_email_combo'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_email_connections_user_email'), 'email_connections', ['user_email'], unique=False)
    op.create_index(op.f('ix_email_connections_email'), 'email_connections', ['email'], unique=False)
    # ### end Alembic commands ###
